<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-P92S73M" ignored="0" name="t2" tests="5" failures="3" timestamp="01 十二月 2020 10:08:03 GMT" time="0.04" errors="0">
  <testcase name="test1" time="0.009" classname="com.webtest.demo.TestCheck"/>
  <testcase name="test2" time="0.001" classname="com.webtest.demo.TestCheck">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.demo.TestCheck.test2(TestCheck.java:17)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.001" classname="com.webtest.demo.TestCheck">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.webtest.demo.TestCheck.test3(TestCheck.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.001" classname="com.webtest.demo.TestCheck"/>
  <testcase name="test5" time="0.001" classname="com.webtest.demo.TestCheck">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at com.webtest.demo.TestCheck.test5(TestCheck.java:32)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
</testsuite> <!-- t2 -->
